version: '3.8'

networks:
  client-side: {}
  server-side: {}

volumes:
  db-data:
  cache:

services:
  backend:
    container_name: workspace
    build:
      context: backend
      dockerfile: Dockerfile
      target: Dev
    networks: server-side

  db:
    container_name: db
    image: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-server", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/redis
    ports: "6379:6379"
    networks: server-side

  proxy:
    container_name: proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks: server-side
    