version: '3.8'

volumes:
  db-data:

services:
  backend:
    container_name: workspace
    build:
      context: backend
      dockerfile: Dockerfile
      target: Dev
    env_file:
      - ./devenv/backend.env
    #  - /backend/.cargo/cargo.env

  db:
    container_name: db
    image: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-server", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/redis
    expose:
      - 6379

  proxy:
    container_name: proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend